feat: permission guard
UEK-i-team/unievent-planner-backend pull request #1
Opened 2024-07-07 19:20 UTC by hamburger231

Added permission guard, decorator and a .enum file with permissions.

2024-07-07 19:22 UTC, hamburger231 commented
nie jestem pewien czy wszystko jest wporządku bo jeszcze się tego uczę, userPermissions to będzie permisja przypisana do użytkownika w db i będzie przyrównywana do permisji bezpośrednio w kodzie, chyba ok approach?

2024-07-07 19:28 UTC, hamburger231 commented
będzie się potem tego nad endpointem w ten sposób korzystało 

@UseGuards(PermissionGuard) i np. @Permission(['admin'])

2024-09-22 19:01 UTC, TheFenix2000 requested changes

2024-09-22 19:01 UTC, TheFenix2000 commented on src/auth/permissions.decorator.ts
> +import { CustomDecorator, SetMetadata } from '@nestjs/common';
ten plik powinien być w folderze decorators w folderze `shared` 
![image](https://github.com/user-attachments/assets/3c0a1d38-9f31-47fc-a199-93ce2d01a1a7)

2024-09-22 19:01 UTC, TheFenix2000 commented on src/auth/permissions.enum.ts
> +import { Subject, Action } from 'src/libs/shared';
to analogicznie tylko w osobnym podfolderze consts i to nei ejst enum bo to klasa wieć const jak już

2024-09-22 19:01 UTC, TheFenix2000 commented on src/auth/permissions.guard.ts
> +import {
ten plik natomiast w internal w folderze guards bo jest używalny w głownym komponencie aplikacji i tylko tam powinien byc ładowany

2024-09-22 19:01 UTC, TheFenix2000 commented on src/app.module.ts
> +  providers: [
to missclick widzę bo 2 razy

2024-09-22 19:01 UTC, TheFenix2000 commented on src/auth/permissions.guard.ts
> +      sessionPermissions.some((perm) => perm.subject === Subject.ALL) &&
to nie jest ok, bo sprawdza 'czy któraś z permisji jest ALL' i 'czy któraś z permisji jest manage' a powinno być czy któaś z permisji jest all && jej action jest manage w jedym ifie

2024-09-22 19:01 UTC, TheFenix2000 commented on src/auth/permissions.guard.ts
> +    permissions: RequiredPermissions[],
to jeżeli to są wymagane permisje to powinno się inaczej nazwyać, tzn. bardziej konkretnie `requiredPermissions`

2024-10-22 19:59 UTC, TheFenix2000 approved these changes

2024-10-22 20:00 UTC, merged