feat: add pipelines for tests
UEK-i-team/unievent-planner-backend pull request #14
Opened 2024-10-02 15:39 UTC by JakubOtto

2024-11-20 18:43 UTC, TheFenix2000 requested changes
Troche poprawek i brakuje częsci taska z budowaneim serwera

2024-11-20 18:43 UTC, TheFenix2000 commented on src/app.controller.ts
do usuniecia

2024-11-20 18:43 UTC, TheFenix2000 commented on package.json
> +    "prepare": "if [ \"$NODE_ENV\" != \"production\" ]; then husky install; fi",
`husky install` jest depreciated, także zostaw poprzednie

2024-11-20 18:43 UTC, TheFenix2000 commented on package.json
> +    "prepare": "if [ \"$NODE_ENV\" != \"production\" ]; then husky install; fi",
Po co ten env tutaj, nie widzę bys go używał gdzieś w pipelinach

2024-11-20 18:43 UTC, TheFenix2000 commented on src/app.module.ts
> +      useFactory: async (configService: ConfigService) => {
Po co nadpisywałeś funkcję którą dodałem do zwracania uri?

2024-11-20 18:43 UTC, TheFenix2000 commented on src/app.module.ts
> +  controllers: [AppController],
do usuniecia

2024-11-20 18:43 UTC, TheFenix2000 commented on src/app.module.ts
> +  controllers: [AppController],
czy po co tu jest ten kontroller?

2024-11-20 18:43 UTC, TheFenix2000 commented on .github/workflows/unit-e2e-tests.yml
> +          MONGODB_HOST: localhost
jak wyzej

2024-11-20 18:43 UTC, TheFenix2000 commented on .github/workflows/unit-e2e-tests.yml
> +          MONGODB_HOST: localhost
podawanie w taki sposób do otwartego repozytorium jakichkolwiek poświadczeń nawet do lokalnych baz danych jest naganne.
Musisz zastosować tu envy juz z githuba

2024-11-20 18:43 UTC, TheFenix2000 commented on .github/workflows/unit-e2e-tests.yml
Przydałoby sie by puszczać testy tylko gdy przejdą w takiej kolejnści workflows:
prettier & eslint (to mamy) -> build production server (tego nie ma tutaj wcale) -> unit tests (to tu masz) -> e2e (to też masz niżej)

Issue jak chgłop robił takie sprawdzanie czy inny workflow przeszedł
https://github.com/orgs/community/discussions/66512

2024-11-20 18:43 UTC, TheFenix2000 commented on .github/workflows/unit-e2e-tests.yml
> +name: CI Pipeline - Tests Only
skoro to unit tests i e2e to nazwij to tak by sie odnosiło do tego i tego

2024-11-20 18:43 UTC, TheFenix2000 commented on .github/workflows/unit-e2e-tests.yml
> +on:
wystarczy tak jak mamy w pierwszym workflow czyli `on: [push]` i potem przed runs-on: jest fajny ifek: `if: github.base_ref != 'develop'` i to załatwia sprawę

2024-11-20 18:43 UTC, TheFenix2000 commented on .github/workflows/unit-e2e-tests.yml
A i oczywiście tam też masz, by dodać to do `main` brancha tak jak dodaliśmy formatting tests

2024-11-20 18:46 UTC, TheFenix2000 commented
Zauważyęłm też zę jak jest na pullu to podwójnei lecą testy na początku co jest bez sensu 
![image](https://github.com/user-attachments/assets/1fca7058-970a-4665-a48c-7cd50b419518)
ale to poprawisz zmieniając triggera

2024-11-20 18:49 UTC, TheFenix2000 commented on .github/workflows/unit-e2e-tests.yml
rebase na developa...

2025-01-08 19:29 UTC, JakubOtto commented on .github/workflows/unit-e2e-tests.yml
> +on:
Czy tutaj jest potrzeba wrzucać to w ten drugi workflow od testów? Skoro mamy już sprawdzenie tego w formatting-tests, a build-prod odpala sie tylko jak formatting-tests zakończy się sukcesem, to chyba nie ma sensu tego znowu sprawdzać?

2025-01-22 03:42 UTC, JakubOtto commented
Hej, nie potrafię tego zrobić, stwierdziłem, że dziś to ogarnę na jutrzejsze spotkanie ale nie ma na to szans. Siedzę od 23 nad tym i cały czas sypie mi błedem authorisation failed.

Błąd tyczy się obu pipelinów, i na builda i na testy bo w obu stawia się mongodb.

Bardzo przepraszam za całą zwłokę i cały syf, ale nie mam pojęcia jak to zrobić

2025-01-22 19:36 UTC, JakubOtto commented
https://github.com/JakubOtto/pipelinestest

2025-02-18 19:36 UTC, TheFenix2000 commented on package-lock.json
to raczej do usunięcia skoro jest drugi

2025-02-18 19:36 UTC, TheFenix2000 commented on .github/workflows/unit-e2e-tests.yml
do usuniecia, jak jest ten drugi z testami

2025-02-19 17:29 UTC, TheFenix2000 submitted a review, later dismissed

2025-02-19 17:37 UTC, TheFenix2000 approved these changes
Teraz git

2025-02-19 17:38 UTC, merged